#ifndef MARBLES_CONFIG_H
#define MARBLES_CONFIG_H

int WINDOW_SIZE_W = 1024;
int WINDOW_SIZE_H = 786;

int BOARD_SIZE_W = 700;
int BOARD_SIZE_H = 700;

int MARBLE_SIZE_W = 50;
int MARBLE_SIZE_H = 50;

int OFFSET_W = 103;
int OFFSET_H = 101;

int DISTANCE_BETWEEN_HOLECENTERS_W = 75;
int DISTANCE_BETWEEN_HOLECENTERS_H = 74;

#endif // MARBLES_CONFIG_H
